# -*- coding: utf-8 -*-
"""positive

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ODp3ybg6BnfA54LV0SdqgiSwZRSNY8sd
"""

#seperating positive numbers from a list
l=[]
l1=[]
n=int(input("Enter the no. of elements you want:"))
for i in range(1,n+1):
  x=int(input())
  l.append(x)
for i in l:
  if i>=0:
    l1.append(i)
print(l1)